### ISSUE TITLE
FS:USER IPC & Tracking FBS

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#23]
### Tracking FBS
- [ ] stb_truetype for GetNearestFontToDesign/MaxHeight using stbtt_GetVFontMetrics
- [ ] Fake vtable for CBitmapFont but still success
- [ ] CFixFlatArray for FontAttrib (looks like used for both Qt and AKN)
- [ ] CBitwiseBitmap declaration and bitmap creation
- [x] Found out usage of FbsSharedChunk and FbsLargeChunk (one is used for storing advance info class globally, one is for storing large bitmap)
- [x] Found out how CBitwiseBitmap detect hardware bitmap, and shared/vs large chunk bitmap (shared type will have iHeap != NULL)
- [x] MBM loading (taken)
   - [x] Run-length decompression (#50)
   - [x] MBM binary parser (ac18fbe5df81dd52aa9e5b23b4ef0b66ebcb6654)
- Implement FBS opcodes:
   -  fbs_load
      * [x] MBM
      * [ ] RSC
- [x] Fill more opcodes, see comment below (good for starters)

### FS:USER IPC

- [ ] EFsAddCompositeMount, ///< Add a mount to the composite file system
- [ ] EFsAddExtension, ///< Adds the specified extension
- [ ] EFsAddFileSystem, ///< Adds a file system
- [ ] EFsAddPlugin, ///< Adds the specified plugin
- [ ] EFsAddProxyDrive, ///< Loads  a proxy drive
- [ ] EFsAllowDismount, ///< Notifies that it is safe to dismount the file system
- [ ] EFsBlockMap, ///< Fetches the BlockMap of a file
- [ ] EFsCheckDisk, ///< -- 60 Checks the integrity of the disk on the specified drive
- [ ] EFsClearPassword, ///< Clears the password from the locked MultiMedia card
- [ ] EFsControlIo, ///< General purpose test interface
- [x] EFsCreatePrivatePath, ///< Creates the private path for a process
- [ ] EFsDebugFunction, ///< Different debugging info
- [ ] EFsDefaultPath, ///< Gets the system default path
- [x] EFsDelete, ///< Deletes file
- [x] EFsDirOpen, ///< Opens a directory
- [x] EFsDirReadOne, ///< -- 50 Reads a single directory entry
- [x] EFsDirReadPacked, ///< Reads all filtered directory entries
- [x] EFsDirSubClose, ///< Closes the directory.
- [ ] EFsDismountExtension, ///< -- 90 Dismounts the specified extension
- [ ] EFsDismountFileSystem, ///< Dismounts the file system from the specified drive
- [ ] EFsDismountPlugin, ///< Dismounts the specified plugin
- [ ] EFsDismountProxyDrive, ///< Dismounts a proxy drive
- [x] EFsDrive, ///< Gets information about a drive and the medium mounted on it
- [x] EFsDriveList, ///< Gets a list of the available drive
- [x] EFsEntry, ///< Gets a file's attributes
- [ ] EFsErasePassword, ///< Erase the password from the locked MultiMedia card
- [ ] EFsExtensionName, ///< Gets the name of the extension on the specified drive
- [x] EFsFileAdopt, ///< Adopts an already open file
- [ ] EFsFileAtt, ///< Gets the file's attributes
- [ ] EFsFileChangeMode, ///< Switches an open file's access mode
- [ ] EFsFileClamp, ///< Disable modification of a specified file in storage media
- [x] EFsFileCreate, ///< Creates and opens a new file
- [x] EFsFileDrive, ///< Gets drive information on which this file resides
- [x] EFsFileDuplicate, ///< Makes a duplicate of this file handle
- [x] EFsFileFlush, ///< Commits data to the storage device
- [x] EFsFileFullName, ///< Gets the full filename
- [ ] EFsFileLock, ///< Locks a region within the file
- [ ] EFsFileModified, ///< Gets local date and time the file was last modified
- [x] EFsFileName, ///< Gets the final part of a filename
- [x] EFsFileOpen, ///< -- 30 Opens file
- [x] EFsFileRead, ///< Reads from the file
- [ ] EFsFileReadCancel, ///< -- 120 Cancels an outstanding asynchronous read request
- [x] EFsFileRename, ///< Renames a file
- [x] EFsFileReplace, ///< Replaces a file of the same name or creates a new file
- [x] EFsFileSeek, ///< Sets the the current file position
- [ ] EFsFileSet, ///< Sets the file’s attributes, last modification date/time
- [ ] EFsFileSetAtt, ///< Sets or clears file attributes
- [ ] EFsFileSetModified, ///< Sets the date and time the file was last modified
- [x] EFsFileSetSize, ///< Sets the file size
- [x] EFsFileSize, ///< -- 40 Gets the current file size
- [x] EFsFileSubClose, ///< Closes the file
- [x] EFsFileSystemName, ///< Gets the name of the file system mounted on the specified drive
- [x] EFsFileTemp, ///< Creates and opens a temporary file
- [ ] EFsFileUnLock, ///< Unlocks a region within the file
- [x] EFsFileWrite, ///< Writes to the file
- [ ] EFsFileWriteDirty, ///< Writes dirty data to disk. Used when write caching enabled
- [ ] EFsFinaliseDrive, ///< Finalise a specific drive
- [ ] EFsFormatNext, ///< Executes the next format step
- [ ] EFsFormatOpen, ///< Opens a device for formatting
- [ ] EFsFormatSubClose, ///< Closes the Format subsession
- [x] EFsGetDriveName, ///<  Gets the name of a drive
- [x] EFsGetLongName, ///< Gets the long filename
- [ ] EFsGetMediaSerialNumber, ///<  Gets the serial number of media
- [ ] EFsGetNotifyUser, ///< Tests user notification of file access failure is in effect
- [ ] EFsGetReserveAccess, ///< Get exclusive access to reserved area
- [x] EFsGetShortName, ///< Gets the short filename
- [ ] EFsInitialisePropertiesFile, ///< Read in the F32 properties file provided by ESTART
- [x] EFsIsFileInRom, ///< Gets a pointer to the specified file, if it is in ROM
- [x] EFsIsFileOpen, ///< Tests whether a file is open
- [ ] EFsIsValidName, ///< Tests whether a filename and path are syntactically correct
- [ ] EFsListOpenFiles, ///< get a list of open files */
- [ ] EFsLoadCodePage, ///< Loads a code page library
- [ ] EFsLockDrive, ///< Locks a MultiMedia card in the specified drive
- [x] EFsMkDir, ///< Makes directory
- [ ] EFsMountExtension, ///< Mounts the the specified extension
- [ ] EFsMountFileSystem, ///< Mounts a file system
- [ ] EFsMountFileSystemScan, ///< Mounts a file system and performs a scan on a drive
- [ ] EFsMountPlugin, ///< Mounts the specified plugin
- [ ] EFsMountProxyDrive, ///< Mounts a proxy drive
- [ ] EFsNotificationAdd, ///< -- 140 Adds filter to the server, comprising a path and notification type
- [ ] EFsNotificationBuffer, ///< Communicates buffer to file server
- [ ] EFsNotificationCancel, ///< Cancels the notification request
- [ ] EFsNotificationOpen, ///< Opens the notification
- [ ] EFsNotificationRemove, ///< Removes filters from Server-Side
- [ ] EFsNotificationRequest, ///< Sends the notification request
- [ ] EFsNotificationSubClose, ///< Closes the notification
- [x] EFsNotifyChange, ///< Notifies file and/or directory change
- [x] EFsNotifyChangeCancel, ///< Cancels change notification
- [x] EFsNotifyChangeCancelEx, ///< Cancels all outstanding requests for notification of change
- [x] EFsNotifyChangeEx, ///< Requests a notification of change to files or directories
- [ ] EFsNotifyDiskSpace, ///< -- 80 Disk space change notification
- [ ] EFsNotifyDiskSpaceCancel, ///< Cancels a specific outstanding notification
- [ ] EFsNotifyDismount, ///< Issues a request to asynchronously dismount the file system
- [ ] EFsNotifyDismountCancel, ///< Cancels a request to asynchronously dismount the file system
- [x] EFsParse, ///< Parses a filename specification
- [ ] EFsPluginDoCancel, ///< Cancels an synchronous plugin request
- [ ] EFsPluginDoControl, ///< Issues a synchronous plugin request
- [ ] EFsPluginDoRequest, ///< Issues an asynchronous plugin request
- [ ] EFsPluginName, ///<-- 110 Gets a plugin's name in specific position and drive
- [ ] EFsPluginOpen, ///< Opens the plugin
- [ ] EFsPluginSubClose, ///< Closes the plugin
- [x] EFsPrivatePath, ///< Creates the text defining the private path
- [ ] EFsQueryVolumeInfoExt, ///< Query interface to retrieve extended volume information
- [ ] EFsRawDiskOpen, ///< Opens a direct access channel to the disk */
- [ ] EFsRawDiskRead, ///< Reads directly from the disk
- [ ] EFsRawDiskWrite, ///< Writes directly to the disk
- [ ] EFsRawSubClose, ///< Closes the direct access channel to the disk
- [ ] EFsReadFileSection, ///< -- 70 Reads data from a file without opening it
- [x] EFsRealName, ///< Gets the real name of a file
- [ ] EFsReleaseReserveAccess, ///< Release exclusive access to reserved area
- [ ] EFsRemountDrive, ///< Forces a remount of the specified drive
- [ ] EFsRemoveExtension, ///< Removes the specified extension
- [ ] EFsRemoveFileSystem, ///< Removes a file system
- [ ] EFsRemovePlugin, ///< Removes the specified plugin
- [ ] EFsRemoveProxyDrive, ///< Unloads a proxy drive
- [x] EFsRename, ///< -- 20 Renames a single file or directory
- [x] EFsReplace, ///< Replaces a single file with another
- [ ] EFsReserveDriveSpace, ///< -- 100 Reserves an area of a drive
- [ ] EFsResourceCount, ///< Gets the number of currently open resources
- [ ] EFsResourceCountMarkEnd, ///< Ends resource count checking
- [ ] EFsResourceCountMarkStart, ///< Marks the start of resource count checking
- [x] EFsRmDir, ///< Removes a directory
- [ ] EFsScanDrive, ///< Checks the specified drive for specific errors and corrects them
- [x] EFsSessionPath, ///< Gets the session path
- [x] EFsSessionToPrivate, ///< Sets the session path to point to the private path
- [ ] EFsSetDefaultPath, ///< Sets the system default path
- [ ] EFsSetDriveName, ///< Sets the name of a drive
- [x] EFsSetEntry, ///< Sets both the attributes and the last modified date and time for a file or directory
- [ ] EFsSetLocalDriveMapping, ///< Set the local drive mapping
- [x] EFsSetNotifyUser, ///< Sets if the user should be notified of file access failure
- [ ] EFsSetSessionFlags, ///< Set/Clear session specific flags
- [x] EFsSetSessionPath, ///< Sets the session path for the current file server client
- [ ] EFsSetStartupConfiguration, ///< Configures file server at startup
- [ ] EFsSetSubst, ///< -- 10, Assigns a path to a drive letter
- [ ] EFsSetSystemDrive, ///< Set SystemDrive
- [ ] EFsSetVolume, ///< Sets the label for a volume
- [ ] EFsStartupInitComplete, ///< Noifies the file server of startup initialisation completion
- [ ] EFsSubst, ///< Gets the path assigned to a drive letter
- [ ] EFsSwapFileSystem, ///< Swaps file systems
- [x] EFsSynchroniseDriveThread, ///< -- 130 Synchronises the asynchronous operation which executes in driver thread
- [ ] EFsUnclamp, ///< Re-enable modification of a specified file in storage media
- [ ] EFsUnlockDrive, ///< Unlocks the MultiMedia card in the specified drive
- [x] EFsVolume, ///< Gets volume information for a formatted device
- [ ] EMaxClientOperations ///< This must always be the last operation insert above

Note that some of these calls can be ignored, and will be removed from this list in the future. The most needed things right now is to implemented basic and functional IPCv2

**Comment by TRR95** [comment]
Reopened to help easily remember what been worked on, that said, it goes into "Near Future" because most of the stuff won't be needed until EKA2L1 team tries to add some vary advanced features (for example, making Device Roms bootable)

furthermore, those reading this, don't expect any vary advanced features anytime soon. this is just list for the Dev's

**Comment by pent0** [comment]
Pretty useless now )) I will close
