### ISSUE TITLE
Tracking ECOM

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#61]
- [x] SPI loader
- [x] ECom RSC info parser
- [x] Init code
- [x] Fix for RSC compressed (i haven't seen it built-in)
- [x] List Implementation and Inistantiate
- Testings
   * [x] ListImplementations
   * [ ] CollectImplementations (reserved for @dramikei)
   * [ ] GetImplementationCreationMethod

**Comment by pent0** [comment]
List implementations won't include custom resolver handling, so we should proceed with normal list implementations with default resolver support asap

**Comment by pent0** [comment]
Need to do test

**Comment by pent0** [comment]
ListImplementations are stable on: ee59ad816c1759d4ee2aa7d1af0a606a41cd5637

CollectImplementations and other edge case (run out of memory) are not tested

**Comment by pent0** [comment]
![image](https://user-images.githubusercontent.com/25717050/53677587-ebee8c00-3ce4-11e9-8fe7-12497a2eab13.png)
